import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Vibhor Saxena's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900">
        {/* Responsive Navbar */}
        <Navbar />

        {/* Main content with padding so it doesn’t overlap fixed Navbar */}
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
